### ISSUE TITLE
Update basic usage in README

### ISSUE THREAD

**Issue by usmanayubsh** [pasqal-io/cloud-sdk#32]
Basic usage needs to be updated, keeping in view recent changes e.g. it says: 
`You can also choose to run your batch on an emulator using the optional argument 'emulator'`

However, there is no such optional `emulator` argument anymore.

**Comment by MatthieuMoreau0** [comment]
Documentation has been updated in https://github.com/pasqal-io/cloud-sdk/pull/33 

Thanks for the report, now closing this issue.
