### ISSUE TITLE
Adding mypy type checking

### ISSUE THREAD

**Issue by CdeTerra** [pasqal-io/cloud-sdk#43]
I'm trying to add type checking when importing CloudSdk, but it seems to be not working because CloudSdk is not fully type checked.

Are you considering to add a `.mypy.ini` file to the project and run `mypy` to fully check the project? This way, users will be able to use CloudSdk's types.

**Comment by MatthieuMoreau0** [comment]
Thanks Clement for this suggestion! That's definitely valuable so we will add this to our backlog. We'll keep you updated.
