### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/cloud-sdk#48]
Hi!

Currently in Pulser we support Python 3.7 or higher, while for the `cloud-sdk` you are starting from Python 3.8.
As we are introducing the `cloud-sdk` as a dependency to the `pulser-pasqal` extension, it would be preferable that the supported Python versions between the two packages match.

Python 3.7 end of life is in 8 months, which puts us in a weird limbo where:
- It's a bit too soon to drop support in Pulser
- It seems useless to add support in the `cloud-sdk` since in 8 months we would be removing it

So, I think the decision here should be made based on how easy it would be to add Python 3.7 support on the `cloud-sdk`. 
- In terms of the `cloud-sdk` dependencies, I checked the supported Python versions of `requests` and `requests-mock` and there seems to be no issue there (they still support >=3.5)
- In terms of Python >=3.8 features, I wonder how much you are using. If it's just special types from typing (I found `Final` and `TypedDict`), it is very easy to workaround (we did it in Pulser). Is there anything else you can think of?

If it turns out it would be easy and you wouldn't mind, I'd be happy to take care of the Python 3.7 support, but I'd like to hear from you first.

Thanks!

**Comment by awennersteen** [comment]
In #49 we'll add a testing pipeline so it wouldn't be much effort to add another Python version in the support matrix to always check that we're keeping Python 3.7 support.

To me it also looks like it's just the typing that needs to adapted to Python 3.7. I can probably give some support for this if any issues occur, but it would be nice to hear from the cloud team.

**Comment by HGSilveri** [comment]
Ok, cool! I already have the changes locally, so I'll open a no-strings-attached draft PR for the Cloud team to go over the necessary modifications.

**Comment by HGSilveri** [comment]
I agree. In the absence of other constraints, I think supporting a version until it reaches its [end of life](https://endoflife.date/python) is a good place to start.
